# CloudPose Kubernetes部署配置 - 阿里云ECS环境
# 适用于阿里云容器服务ACK或自建Kubernetes集群

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudpose-deployment
  namespace: default
  labels:
    app: cloudpose
    version: v1
spec:
  replicas: 1  # 初始副本数，实验时会动态调整为1,2,4,8
  selector:
    matchLabels:
      app: cloudpose
  template:
    metadata:
      labels:
        app: cloudpose
        version: v1
    spec:
      containers:
      - name: cloudpose
        image: backend-cloudpose-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: FLASK_ENV
          value: "production"
        - name: WORKERS
          value: "4"  # Gunicorn worker数量
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            cpu: "0.5"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      # 使用本地构建的镜像，无需镜像拉取密钥
      # 节点选择器（可选）
      nodeSelector:
        kubernetes.io/os: linux
      # 容忍度配置（可选）
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: cloudpose-service
  namespace: default
  labels:
    app: cloudpose
  # 本地Kubernetes集群配置
  annotations: {}
spec:
  type: NodePort  # 本地集群使用NodePort
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: cloudpose

---
# HorizontalPodAutoscaler - 水平Pod自动扩缩容
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloudpose-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudpose-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60

---
# ConfigMap - 配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudpose-config
  namespace: default
data:
  app.conf: |
    # CloudPose应用配置
    DEBUG=False
    LOG_LEVEL=INFO
    MAX_CONTENT_LENGTH=16777216  # 16MB
    UPLOAD_TIMEOUT=30

---
# Secret - 敏感信息（如需要）
apiVersion: v1
kind: Secret
metadata:
  name: cloudpose-secret
  namespace: default
type: Opaque
data:
  # 如果有API密钥等敏感信息，在这里配置
  # api-key: <base64-encoded-value>

---
# NetworkPolicy - 网络策略（可选）
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloudpose-netpol
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: cloudpose
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53  # DNS
    - protocol: UDP
      port: 53  # DNS
  - to: []
    ports:
    - protocol: TCP
      port: 443  # HTTPS
    - protocol: TCP
      port: 80   # HTTP