version: '3.8'

services:
  cloudpose-api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: cloudpose-api
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - MODEL_PATH=/app/model/movenet-full-256.tflite
    volumes:
      # Optional: mount log directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
          

networks:
  default:
    name: cloudpose-network